name: Fetch Remote Files

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: ~

jobs:
  Fetch-Remote-Files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Fetch Remote Files
        run: |
          export FILE_PATH="${{ vars.FILE_PATH }}"
          python main.py
          python achievements.py
          cp src/calendar.json Resources/calendar.json
          cp src/birthday.json Resources/birthday.json

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          push: '--force'
          new_branch: 'remote'
          message: ':sparkles: Fetch Remote Files'
          add: |
            'Resources'
